### ISSUE TITLE
doctests

### ISSUE THREAD

**Issue by Miradorn** [jfpedroza/neotest-elixir#11]
Hey there, thanks for the great plugin!

Bit in a hurry right now, so just wanted to let you know that it seems that doctests are not fully supported (not listed in test summary, no indicator in signs?)
Let me know if I can help with this!

**Comment by jfpedroza** [comment]
Hey!

Yeah, support for doctests was missing, I just hadn't gotten around to add it.

It was rather simple, so just added it. Let me know what you think.

For now, the doctests appear as a single test, the same way dynamic tests are handled.

I'm working improving that for dynamic tests, and the change will apply to doctests too.

**Comment by Miradorn** [comment]
Thanks, freat work!
