### ISSUE TITLE
No IO.inspect and the likes in the output window when assertion fails

### ISSUE THREAD

**Issue by mracos** [jfpedroza/neotest-elixir#15]
Hi 👋 

Firstly, thank you so much for this plugin. It's what made me switch over from `vim-test` to `neotest`. 💙

Not sure if this question is a better fit here or in the neotest repo, but I don't see the output of `IO.inspect` (or `IO.puts` FWIW) on the test `output` window when some assertion fails. Maybe I have the wrong expectations for the output? Missing a configuration? 

![Screenshot 2022-11-21 at 15 17 24](https://user-images.githubusercontent.com/14015177/203130449-105c0f58-34e6-4c16-9d7f-acfc0170ca9f.png)
![Screenshot 2022-11-21 at 15 17 14](https://user-images.githubusercontent.com/14015177/203130454-a03a0963-85e7-47dd-89ce-15659074d084.png)

**Comment by jfpedroza** [comment]
ExUnit doesn't support output capture to show it on failure like Pytest does. It only supports log capture (which is supported by the adapter).

The output you see for the test on failure is not from stdout, it's from formatting the failure in an ExUnit formatter. On the other hand, for successful tests there is no output, so I set the output to the process output (if another test fails you will see it in the output of the successful test).

**Comment by mracos** [comment]
Oh, got it, that's a bummer 😞

Just to rule out, within the adapter, we would not be able to get the "process" output right? I assume that would be too hard 😞

Nevertheless, thank you so much for the explanation, learned something new today!

**Comment by jfpedroza** [comment]
We can get the process output after it finishes, and we could append it to all failing tests, but it would only work well if you disable the default ExUnit formatter, as otherwise you would see the full test output in the output of every failing test.
