### ISSUE TITLE
Unable to run test with asdf and system elixir

### ISSUE THREAD

**Issue by fuelen** [jfpedroza/neotest-elixir#16]
Hello

Thank you for this awesome adapter.
I'm trying to integrate it into my workflow and here is the error I've found.
Steps to reproduce:
* install elixir, erlang and asdf
*
  ```
  $ asdf global elixir system
  ```
*
  ```
  $ asdf global erlang system
  ```
* try to run some test using neotest plugin
* the test is failed and output is the following
```
** (SyntaxError) /home/artur/.asdf/shims/mix:3:18: syntax error before: '.'
    |
  3 | exec /home/artur/.asdf/bin/asdf exec "mix" "$@" # asdf_allow: ' asdf '
    |                  ^
    (elixir 1.14.0) lib/code.ex:1245: Code.require_file/2
```

everything is OK if I specify elixir version from asdf and not the system one.

**Comment by jfpedroza** [comment]
Tests are run using `elixir -S mix ...` and not `mix ...`. The first one executes `elixir`, which finds `mix` in path and executes it as an Elixir script. But with asdf, `mix` is a shell script, so it fails to compile.

Somehow, when you use a version from asdf, `elixir` resolves `mix` to the real script and not the shim, so it has no issues. I think this is a bug in asdf. You can even run `elixir -S mix` in a shell and see the same error.

Try opening an issue in the [asdf-elixir](https://github.com/asdf-vm/asdf-elixir) repo.

**Comment by fuelen** [comment]
Yes, you're right. I see there is a similar issue there which is currently open. I'll close this one for now.
