### ISSUE TITLE
Tests with function calls in the name are not found

### ISSUE THREAD

**Issue by fuelen** [jfpedroza/neotest-elixir#17]
```elixir
defmodule MyTest do
  use ExUnit.Case

  test inspect(&MyModule.hello/1) do
    # ...
  end
end
```

^Such tests are not found.
The same, but with interpolation, works okay:
```elixir
  test "#{inspect(&MyModule.hello/1)}" do
```

**Comment by jfpedroza** [comment]
I hadn't seen test names with arbitrary expressions like that. I'll add support for it.

**Comment by fuelen** [comment]
I use it quite a lot to have module, function and arity in sync with implementation. Thanks :)

**Comment by jfpedroza** [comment]
Supporting arbitrary calls turned out to be quite tricky, probably requires a refactor. Similar to #19.

But I managed to support the specific case "inspect" because it results on a somewhat predictable test name.

**Comment by fuelen** [comment]
@jfpedroza Thanks! This helps a lot.
I'd like to ask support this for `describe` as well :)

**Comment by jfpedroza** [comment]
Makes sense. I just realized we don't support dynamic describes at all.

Can you open a separate issue for that? :)

**Comment by fuelen** [comment]
Sure
