### ISSUE TITLE
Multiline test names

### ISSUE THREAD

**Issue by fuelen** [jfpedroza/neotest-elixir#20]
If test name contains `\n` symbols, then such tests are not found by the adapter:
```elixir
  test "new\nline" do
```

In case of multiline (heredoc strings), UI representation is not great:
```
test """
  new
  line
  """ do
```
![image](https://user-images.githubusercontent.com/588762/213515108-1093a297-861e-4d29-a160-69e482b46345.png)

I suggest replacing new lines with spaces, as it is done in Elixir for tests with `--trace` option https://github.com/elixir-lang/elixir/pull/11728/files

**Comment by jfpedroza** [comment]
@fuelen This was just implemented. Please give it a try.

**Comment by fuelen** [comment]
works fine, thank you
