### ISSUE TITLE
Is this repository still being maintained?

### ISSUE THREAD

**Issue by scottming** [jfpedroza/neotest-elixir#26]
If you don't have much time, I'd happily become a maintainer. 

I want to add more tests to make maintenance of this repository easier. Additionally, I would like to remove support for mix_test_interactive because neotest's watch feature is really great.

**Comment by jfpedroza** [comment]
Hey. As I replied in the email, I plan to resume work on this, but I can give you access to the repo.

I will give Neotest watch a try and see if mix_test_interactive can be removed.

**Comment by scottming** [comment]
> As I replied in the email

Sorry, I missed that email. I saw it right now, thanks.

> I plan to resume work on this

That's great. 

> but I can give you access to the repo.

Thanks.

> I will give Neotest watch a try and see if mix_test_interactive can be removed.

One thing I want to mention is Neotest's watch needs the test code to rely on the product code directly.

For example:

```elixir
alias ProductCodeModule
```

This way will watch the `ProductCodeModule`, but 

```elixir
module = ProductCodeModule
alias module
```

won't.

And I haven't test it with ElixirLS, but Lexical works well.

**Comment by jfpedroza** [comment]
I've invited you to the repo.

**Comment by scottming** [comment]
Thanks again.
