### ISSUE TITLE
Tests with shortened do: blocks are not detected

### ISSUE THREAD

**Issue by jcowgar** [jfpedroza/neotest-elixir#29]
In the example test file below, "test 1" is detected, but "test 2" is not. As soon as you convert "test 2" to a full do/end block, it then is detected. Convert "test 1" to a do: block, and it is no longer detected.

```
describe "my tests" do
  test "test 1" do
    assert true
  end

  test "test 2", do: assert false
end
```

**Comment by jfpedroza** [comment]
This is now supported. Never occurred to me to make a test with an inline body.
